# Generated by Django 3.2.5 on 2021-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='Doe', max_length=30),
        ),
    ]
