# Generated by Django 3.2.5 on 2021-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dicsiplines',
            field=models.JSONField(default=[]),
        ),
    ]
