# Generated by Django 3.2.5 on 2021-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210704_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='group',
            name='teachers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dicsiplines',
            field=models.JSONField(default=list),
        ),
    ]
